### ISSUE TITLE
lycophron files

### ISSUE THREAD

**Issue by myrmoteras** [plazi/lycophron#12]
@punkish @tcatapano @slint 
here are some more files that could be the missing progam files in the repo. Can you please check out?
https://drive.google.com/drive/folders/1-Bm1ihJtZdTLOd35iXd-TFd60aKATYZJ

**Comment by slint** [comment]
Files checked during the Feb 2023 sprint, and are not needed. Some of the diagrams might be useful for documentation later on, but that's a much later task (will create an issue in this repository for it and link here).
