### ISSUE TITLE
upload bat files  from sandbox to production

### ISSUE THREAD

**Issue by myrmoteras** [plazi/lycophron#22]
Hi Donat and @flsimoes , 

Manuel finished last week the Sandbox upload of the ~230 records bats collection from the Google Sheet Felipe and Juliana shared in the last Arcadia sprint. 

- Everything was uploaded in a separate Zenodo community at [https://sandbox.zenodo.org/communities/bats_project/search](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsandbox.zenodo.org%2Fcommunities%2Fbats_project%2Fsearch&data=05%7C01%7C%7C46175c2a29dc42aa8f3008db3461ae21%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C638161366367181325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eIl1GYD6d8XFYhuGDwRQIH26iaGDzfm9bBXDhdDd3aE%3D&reserved=0). If you agree with this method of organisation, we could do the same when we perform the final upload on the production system. You can create the Zenodo community under the BLR Zenodo account and add any extra information in the description. As discussed before we can include the records also in the classic BLR community.
- The Google sheet used for the import and upload via Lycophron is at [https://docs.google.com/spreadsheets/d/19T3S6kKJyVJpe7lgd5GKYKLfZXMCTZhgo6d0N8EhfIk/edit](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F19T3S6kKJyVJpe7lgd5GKYKLfZXMCTZhgo6d0N8EhfIk%2Fedit&data=05%7C01%7C%7C46175c2a29dc42aa8f3008db3461ae21%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C638161366367181325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RHsAfqcEOCO3JvyEt3awZMDx1tdKcwku1CE40%2BF4ynw%3D&reserved=0)

Some pending action items before we go ahead with uploading to production:

- You’ll notice that the community includes 225 records, while the Google sheet has 239 rows (240 - 1 header).
    - 5 records with existing DOIs were already uploaded from previous tries
    - 5 records had an invalid affiliation value, but we can clean this up in the Google sheet
- 45 entries in the Google sheet were missing DOIs, but we uploaded them anyways to verify the metadata: [https://sandbox.zenodo.org/communities/bats_project/search?q=_exists_:conceptdoi](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsandbox.zenodo.org%2Fcommunities%2Fbats_project%2Fsearch%3Fq%3D_exists_%3Aconceptdoi&data=05%7C01%7C%7C46175c2a29dc42aa8f3008db3461ae21%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C638161366367337546%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FdMgOO4gppLD5pNSBwlTNAHwJgYRRJbyhuaZ6rbOmUg%3D&reserved=0)
- The metadata on the records (or at least a sample of them) has to be verified, just to make sure we didn’t mess up anything in the process. These are metadata-only updates which is fine to also perform later on (even after the production upload).

Let me know if you have any questions, I’ll be off next week on holidays, but we can re-route to the rest of the team so they can help.

Cheers,
Alex

PS: I couldn’t find Juliana’s email address, so feel free to forward this or add her in the loop.

**Comment by myrmoteras** [comment]
https://sandbox.zenodo.org/record/1179813#.ZC2SGXZBz8A
* missing author

**Comment by myrmoteras** [comment]
https://sandbox.zenodo.org/record/1179813#.ZC2S03ZBz8B

seems to be recurring issue

(<i>Boa constrictor orophias</i>)

remove tags in title  
![image](https://user-images.githubusercontent.com/4609956/230128423-eca8771f-2e61-45b7-a540-6ba15bca6a5c.png)

**Comment by myrmoteras** [comment]
@slint can you add the files of this bat upload NOT to the `bats_project` a new bat to the `biosyslit`, `coviho` and the `globalbioticinteractions`

**Comment by slint** [comment]
Regarding communities, yes we can add both the `biosyslit` and `coviho` communities.

For the GloBi community though, it's Jorrit who is curating it, in which case he will have to accept all the record inclusion requests (we can also do this on our side quickly for all of them if he agrees).

**Comment by myrmoteras** [comment]
@slint  [@Donat Agosti](https://covid19taf.slack.com/team/U011523KWUT)
 please feel free to automatically submit the docs to the globalbioticinteractions zenodo community. We can auto-accept if needed.

**Comment by myrmoteras** [comment]
Regarding Lycophron, I agree we can proceed with pushing to production. There were though a couple of clean-up tasks still (there are some HTML tags in titles, missing DOIs, etc.), that we can’t do on our side without the domain knowledge. We can revive the GitHub issue and ping the right people. Afterwards Manuel can close it up and make the run (and also automatically add it to the GloBi community as well).

@flsimoes can you tell @juwingert to look into this issue?

**Comment by flsimoes** [comment]
> * https://docs.google.com/spreadsheets/d/19T3S6kKJyVJpe7lgd5GKYKLfZXMCTZhgo6d0N8EhfIk/edit

I do not have access to the spreadsheet in question

**Comment by juwingert** [comment]
> > * https://docs.google.com/spreadsheets/d/19T3S6kKJyVJpe7lgd5GKYKLfZXMCTZhgo6d0N8EhfIk/edit
> 
> I do not have access to the spreadsheet in question

Me neither.

**Comment by slint** [comment]
I'm sorry, can you try again here: https://docs.google.com/spreadsheets/d/19T3S6kKJyVJpe7lgd5GKYKLfZXMCTZhgo6d0N8EhfIk/edit?usp=sharing

**Comment by juwingert** [comment]
@slint @myrmoteras I changed the <i> tag to <em> in column A and added some missing DOIs, is that it?

**Comment by slint** [comment]
- Regarding the HTML tags, they need to be completely removed from the titles, since they're not actually supported, and are rendered as regular text on the record page
- For the missing DOIs, if there is no known corresponding DOI, then they don't have to be filled-in and we will register a Zenodo DOI for them

**Comment by flsimoes** [comment]
> * Regarding the HTML tags, they need to be completely removed from the titles, since they're not actually supported, and are rendered as regular text on the record page

Ah ok, I don't recall why, but when Marcus started development on Lycophron he asked us to fill the HTML tags.

**Comment by juwingert** [comment]
> * Regarding the HTML tags, they need to be completely removed from the titles, since they're not actually supported, and are rendered as regular text on the record page 
        
       OK, I removed them.

>     * For the missing DOIs, if there is no known corresponding DOI, then they don't have to be filled-in and we will register a Zenodo DOI for them

       I completed two or three DOI's, only the ones I undoubtedly had.

**Comment by slint** [comment]
> Ah ok, I don't recall why, but when Marcus started development on Lycophron he asked us to fill the HTML tags.

For the `description` column that is good, since we render the HTML.

---

Thanks a lot for having a look and fixing the entries @juwingert and @flsimoes, we are ready to upload it on production now. The team is a bit swamped this week, but I think we can have it up by the end of next week. I'll respond here, with links to the records.

**Comment by myrmoteras** [comment]
@slint very good. Let us know. We are having a second part of the bat publications for this Covid-related bat corroosting project by next week, so we can prepare them for a next upload

Also, please make sure that the upload is to BLR and covihio community, and that we have to admin rights, becuase we eventually will process those files to move them also into biodivPMC at SIBiLS.

tx

**Comment by myrmoteras** [comment]
> For the `description` column that is good, since we render the HTML.

@slint the reason the emphasis are in the text is because these are taxonomic names. May be later this could be used to format taxonomic names in the title of the deposit?

**Comment by myrmoteras** [comment]
@slint can we move this now into production, so we have this done? tx

**Comment by slint** [comment]
@myrmoteras, @alejandromumo has uploaded the records up in production! We've managed to narrow them down using [this search query](https://zenodo.org/communities/biosyslit/search?page=1&size=20&q=created:2023-08-01%20AND%20communities:(biosyslit%20AND%20coviho)&subtype=article&access_right=open), in case you want to share.

Two things missing:

- We need to accept them to the GloBi community (will soon run a script to do so automatically)
- One of the records from the Google Sheet was already uploaded in the past on BLR (I guess via the usual workflow, since it has lots of links): https://zenodo.org/record/4588432 (https://doi.org/10.1038/s41598-020-64159-1)

**Comment by myrmoteras** [comment]
@alejandromumo  @slint 
thanks for this. Is there a way to get this upload selected and or viewed, that is, give me all the articles of this batch upload? Or would we need to add a special keyword or similar to it?

**Comment by myrmoteras** [comment]
@slint I understand, that we also could add keywords, or custom keywords. Is this right?

**Comment by slint** [comment]
> Is there a way to get this upload selected and or viewed, that is, give me all the articles of this batch upload? Or would we need to add a special keyword or similar to it?

Right now, the search query I shared above was basically "open access articles from 2023-08-01 that are in BLR, COVIHO, and GloBi", which narrows it down to the exact set. But I agree, that's not a very trivial differentiating factor. That's why originally we proposed placing these either in a new Zenodo community (as if they were a specific "collection" of sorts), or maybe marking them with a keyword (or even better if there was a DarwinCore custom field that could describe them all).

> @slint I understand, that we also could add keywords, or custom keywords. Is this right?

Yes, all of the Zenodo metadata fields are supported in the input CSV.

> another question is, do we have a list of CSV or similar in which we have the Zenodo ID added to the bibliographic records?

I think @alejandromumo keeps the Zenodo ID in the Lycophron database file, so we could make an export.

**Comment by alejandromumo** [comment]
@myrmoteras  @flsimoes  @slint 

Find below the sheet with the results of the run in prod: [link](https://docs.google.com/spreadsheets/d/16F1Ay6Xl9SBNZUvfIGpxkSVcee0vYxG09Iufvw7Wx-o/edit#gid=808951872)

It is currently private so I will accept your access requests as soon as you send them.

**Comment by myrmoteras** [comment]
@alejandromumo can we share the link with the COVID task force group to show them? Or may be just make it open for viewing?

**Comment by myrmoteras** [comment]
I would just make it public as is for viewing. It is interesting for this group to look at the structure and granularity.

**Comment by myrmoteras** [comment]
@alejandromumo would it be possible to get the Zenodo deposition ID  linked to the original XLS file, which includes the bibibliographic data?

**Comment by myrmoteras** [comment]
@alejandromumo @slint 

we are running a publisher workshop in Carouge on Sept 14/15, where Lars will participate. Is it possible that we could have a version of Lycorphron there, including the write back of the Zenodo id into the original source file, so we can refer to it?

I would bring this to the attention of the audience that authors or publishers could just upload all the articles to BLR so they have all their articles 
1. with a DOI if not available
2. ready for further processing
3. processed through TB, either directly through the webhook or via TB and thus have also the data there in FAIR. 
3 is essentially the next step of TNA in BiCIKL

Thanks
